# Generated by Django 2.2 on 2019-06-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gii_django_blog', '0002_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_raw',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
