# Generated by Django 3.0.4 on 2020-03-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gii_django_blog', '0009_auto_20190823_0656'),
    ]

    operations = [
        migrations.RunSQL('DROP TABLE IF EXISTS gii_django_blog_post CASCADE;'),
        migrations.RunSQL('DROP TABLE IF EXISTS gii_django_blog_file CASCADE;'),
        migrations.RunSQL('ALTER TABLE IF EXISTS django_gii_blog_post RENAME TO gii_django_blog_post;'),
        migrations.RunSQL('ALTER TABLE IF EXISTS django_gii_blog_file RENAME TO gii_django_blog_file;'),
    ]
