# Generated by Django 3.0.4 on 2020-03-24 04:10

from django.db import migrations, connection


def rename_media_url(apps, schema_editor):

    update_datas = []
    with connection.cursor() as cursor:
        cursor.execute('select * from "gii_django_blog_file"')

        for row in cursor.fetchall():
            row_id, field, *_ = row
            if field.startswith('django_gii_blog'):
                new_field = field.replace('django_gii_blog', 'gii_django_blog', 1)
                update_datas.append((new_field, row_id))

    if not update_datas:
        return

    with connection.cursor() as cursor:
        cursor.executemany(
            'update "gii_django_blog_file" set "field" = %s where "id" = %s',
            update_datas
        )


class Migration(migrations.Migration):

    dependencies = [
        ('gii_django_blog', '0010_auto_20200323_0927'),
    ]

    operations = [
        migrations.RunPython(rename_media_url, migrations.RunPython.noop)
    ]
