# Generated by Django 2.2.3 on 2019-08-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_blog', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_text_raw',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_text',
            field=models.TextField(blank=True),
        ),
    ]
