# Generated by Django 2.2.3 on 2019-08-23 03:20

from django.db import migrations


def fill_short_text_raw(apps, schema_editor):
    Post = apps.get_model('django_gii_blog', 'Post')

    for post in Post.objects.all():
        post.short_text_raw = post.short_text
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_blog', '0007_auto_20190823_0620'),
    ]

    operations = [
        migrations.RunPython(fill_short_text_raw)
    ]
