# Generated by Django 2.2.3 on 2019-08-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_blog', '0008_auto_20190823_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_text_raw',
            field=models.TextField(),
        ),
    ]
